[[plugins]]
repo = 'rebelot/kanagawa.nvim'
hook_add = 'colorscheme kanagawa'

[[plugins]]
repo = 'Shougo/ddc.vim'
hook_add = """
" ddc settings
call ddc#custom#patch_global('sources', ['around'])
call ddc#custom#patch_global('sourceOptions', {
			\ '_': { 'matchers': ['matcher_head'], 'sorters': ['sorter_rank'], 'converters': ['converter_remove_overlap'] },
			\ 'nvim-lsp': {'mark': 'L', 'forceCompletionPattern': '\.\w*|:\w*|->\w*' },
			\ 'around': {'mark': 'A'}})
inoremap <silent><expr> <TAB> ddc#map#pum_visible() ? '<C-n>' : (col('.') <= 1 <Bar><Bar> getline('.')[col('.') - 2] =~# '\s') ? '<TAB>' : ddc#map#manual_complete()
call ddc#enable()"
"""

[[plugins]]
repo = 'williamboman/nvim-lsp-installer'
hook_add = "lua << EOF
local lsp_servers = require('nvim-lsp-installer.servers')
local languages = {'vimls', 'taplo'}
for _,language in ipairs(languages) do
	local isAvailable, server = lsp_servers.get_server(language)
	if not isAvailable then
		error(string.format('%s is not available.', language))
		return
	end

	server:on_ready(function()
	local opts = {}
		if server.name == 'vimls' then
			opts.filetypes = {'vim'}
		end
		if server.name == 'taplo' then
			opts.filetypes = {'toml'}
		end
		server:setup(opts)
	end)

	if not server:is_installed() then
		server:install()
	end
end
EOF"
